### ISSUE TITLE
Error updating KeyCombiner Desktop from 0.3.0 on macOS

### ISSUE THREAD

**Issue by elchead** [tkainrad/keycombiner#30]
Error:
```Error: Cannot download "https://keycombiner.com/download/KeyCombiner-0.3.2-mac.zip", status 404: 
    at ClientRequest.<anonymous> (/Users/adria/Applications/KeyCombiner.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:250:26)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6254)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```
OS: macOS 10.16

**Comment by tkainrad** [comment]
Thank you for reporting this problem!

Unfortunately, I am not sure what it means. Could you describe what you did when it happened? My best guess is that it has something to do with auto-updating. Does updating work when you trigger it through _File->Check for Updates_?

**Comment by elchead** [comment]
Sorry, I used the Check for Update feature and got this error.

I then installed the new version manually and it worked.

It is not severe so I close the issue :)

**Comment by tkainrad** [comment]
Thanks for this additional information. If you don't mind, I reopen the issue again until I understand the problem a bit better. I think it has to do with specific kinds of network problems that will lead to this very ugly error instead of a proper message and a chance to do it again. Re-opening the issue also gives other users a chance to add additional info.

Glad a manual update worked for you!
