### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR when updating on Windows from 0.4.0

### ISSUE THREAD

**Issue by lindseyesch** [tkainrad/keycombiner#61]
Error:
```
Error: net::ERR_HTTP2_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```
OS: Windows NT 10.0.22000

**Comment by tkainrad** [comment]
Thanks for filing this bug report! I suspect this happens when trying to auto-update?

Is there anything about your networking setup that is out of the ordinary? In any case, I will try to find the cause of this problem. Until then, please manually download and install the newest version from https://keycombiner.com/desktop/. It should ask you whether you want to remove the previous installation. Your settings and maybe even login information should be kept this way.

**Comment by tkainrad** [comment]
I just installed 0.4.0 on a Windows machine and tried to update. It worked without issue. I am really sorry, but I don't think I will be able to debug this until some more people have this problem and we find a common pattern.

**Comment by lindseyesch** [comment]
Yeah it was during an auto update. My internet is pretty normal. No vpn or
proxy or anything. 👍

**Comment by lindseyesch** [comment]
No problem! Thanks for the response.

**Comment by tkainrad** [comment]
I see, thanks for reporting back! Maybe something minor like a briefly interrupted connection. Would be interesting if it works if you manually tried to trigger the process again through _File->Check for Updates_. No worries though if you already updated manually. 

I will leave the issue open so others that may face the same problem can contribute.
